### ISSUE TITLE
New version 2.0.7 is not available to use in Flutter

### ISSUE THREAD

**Issue by dharmik-ghelani** [fryette/webview_cookie_manager#73]
I see new version 2.0.7 is published and seeing entry in CHANGELOG.MD also, but its not available in flutter plugin [changelog](https://pub.dev/packages/webview_cookie_manager/changelog), can we push update there also. 

Meanwhile work around may be try to use specific commit as direct dependancy.

**Comment by namnh-0652** [comment]
@fryette Could you help to re-publish the latest code? the latest pubspec version is still 2.0.6 from 2 years ago?

**Comment by namnh-0652** [comment]
@fryette could you help to check?

**Comment by ethicnology** [comment]
In your `pubspec.yaml` this would be equivalent to the `2.7.0` release

```yaml
  webview_cookie_manager:
    git:
      url: https://github.com/fryette/webview_cookie_manager.git
      ref: e03954491a6952e04d7fceeae4c4d074392c0fe2
```
